---
title: "Discriminant"
author: "Yakup Tarık AÇAN"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(car)
library(broom)
library(dplyr)
library(tidyr)
library(haven)
library(readxl)
library(corrplot)
library(funModeling)
library(rstatix)
library(biotools)
library(MASS)
library(klaR)
library(ggplot2)
```

```{r}
pizza_marka <- read_excel("Pizza_data.xlsx")
pizza_marka<-as.data.frame(pizza_marka)
summary(pizza_marka)
pizza_marka$brand<-factor(pizza_marka$brand)
pizza_marka$fat_cat[pizza_marka$fat < 15.65] <- "DUSUK"
pizza_marka$fat_cat[pizza_marka$fat >= 15.65 & pizza_marka$fat < 20.3]<- "ORTA"
pizza_marka$fat_cat[pizza_marka$fat >= 20.3]<- "YUKSEK"
pizza_marka$fat_cat<-factor(pizza_marka$fat_cat)
summary(pizza_marka)
```

```{r}
boxM(pizza_marka[,2:5], pizza_marka$fat_cat)
```

```{r}
pizza_lda<-lda(fat_cat~., data=pizza_marka) 
pizza_lda
```

```{r}
pizzapred<-predict(pizza_lda)
```

```{r}
ldahist(pizzapred$x[,1], g = pizza_marka$fat_cat) 
ldahist(pizzapred$x[,2], g = pizza_marka$fat_cat) 
```

```{r}
tablo_car<-table(pizza_marka$fat_cat,pizzapred$class)
tablo_car
```

```{r}
classrate_pizza<-sum(diag(tablo_car))/sum(tablo_car)
classrate_pizza
```

```{r}
as.vector(pizza_lda$prior[1]^2 + pizza_lda$prior[2]^2 + pizza_lda$prior[3]^2)
```

```{r}
comp_pizza<-cbind(pizza_marka$fat_cat,pizzapred$class)
```

```{r}
pizza_marka %>%
  mutate(LD1 = predict(pizza_lda)$x[, 1],
         LD2 = predict(pizza_lda)$x[, 2]) %>%
  ggplot(aes(LD1, LD2, col = fat_cat)) +
  geom_point()
```

