---
title: "Kümeleme Analizi"
author: "Yakup Tarık AÇAN"
date: "29 01 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(modelr)    
library(broom)     
library(ggpubr)
library(rstatix)
library(car)
library(broom)
library(dplyr)
library(tidyr)
library(haven)
library(readxl)
library(corrplot)
library(matlib)
library(ResourceSelection)
library(DescTools)
library(cvms)
library(ggplot2)
library(MASS)
library(broom)
library(tibble)
library(mlogit)
library("DescTools")
library(nnet)
library(dendextend) 
library(factoextra)
```
```{r}
pizza_marka <- read_excel("Pizza_data.xlsx")
pizza_marka<-as.data.frame(pizza_marka)
summary(pizza_marka)
pizza_marka$fat_cat[pizza_marka$fat < 15.65] <- "DUSUK"
pizza_marka$fat_cat[pizza_marka$fat >= 15.65 & pizza_marka$fat < 20.3]<- "ORTA"
pizza_marka$fat_cat[pizza_marka$fat >= 20.3]<- "YUKSEK"
pizza_marka$brand<-factor(pizza_marka$brand)
pizza_marka$fat_cat<-factor(pizza_marka$fat_cat)
summary(pizza_marka)
```

```{r}
d <- dist(pizza_marka[,c(-1,-9)], method = "euclidean") # uzaklik matrisi
fit <- hclust(d, method="complete") # method= "single", "complete", "average", "ward.D", "centroid"
dend<-as.dendrogram(fit) # Dendogram çizimi
plot(dend)
plot(color_branches(dend, k=2))
```

```{r}
res.hc <- hclust(d,  method = "ward.D2")
fviz_dend(res.hc, cex = 0.5, k = 2, palette = "jco") 
```

k-means
```{r}
fviz_nbclust(pizza_marka[,c(-1,-9)], kmeans, method = "wss")
```

```{r}
set.seed(95739487) 
km.res <- kmeans(pizza_marka[,c(-1,-9)],4, iter.max=10, algorithm="Lloyd")### initial[,-1] başlangıç kümelerini seçmek isterseniz
t(km.res$centers) #Cluster means = SPSS'teki Final Cluster Centers
```
```{r}
library(cluster)
clusplot(pizza_marka[,c(-1,-9)], km.res$cluster, main='2D representation of the Cluster solution',
         color=TRUE, shade=TRUE,
         labels=2, lines=0)
```
```{r}
fviz_cluster(km.res, data = pizza_marka[,c(-1,-9)], palette = "jco",
             ggtheme = theme_minimal())
```

```{r}
pizza_marka$cluster<-km.res$cluster # Veriye gözlemin atandigi kumenin eklenmesi
pizza_marka$cluster<-as.factor(pizza_marka$cluster)

```

```{r}
library(rstatix)
#Anova tablosu
cal_aov <- aov(cal ~ cluster, data = pizza_marka)
summary(cal_aov)
sodium_aov <- aov(sodium ~ cluster, data = pizza_marka)
summary(sodium_aov)
fat_aov <- aov(fat ~ cluster, data = pizza_marka)
summary(fat_aov)
carb_aov <- aov(carb ~ cluster, data = pizza_marka)
summary(carb_aov)
```


