---
title: "Lojistik Regresyon Çıktısı"
author: "Yakup Tarık AÇAN"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(modelr)    
library(broom)     
library(ggpubr)
library(rstatix)
library(car)
library(broom)
library(dplyr)
library(tidyr)
library(haven)
library(readxl)
library(corrplot)
library(matlib)
library(ResourceSelection)
library(DescTools)
library(cvms)
library(ggplot2)
library(MASS)
library(broom)
library(tibble)
library(mlogit)
library("DescTools")
library(nnet)
options(scipen = 99)
```

```{r}
pizza_marka <- read_excel("Pizza_data.xlsx")
pizza_marka <- as.data.frame(pizza_marka)
summary(pizza_marka)
pizza_marka$fat_cat[pizza_marka$fat < 15.65] <- "DUSUK"
pizza_marka$fat_cat[pizza_marka$fat >= 15.65 & pizza_marka$fat < 20.3] <- "ORTA"
pizza_marka$fat_cat[pizza_marka$fat >= 20.3] <- "YUKSEK"
pizza_marka$brand<-factor(pizza_marka$brand)
pizza_marka$fat_cat<-factor(pizza_marka$fat_cat)
summary(pizza_marka)
```

```{r}
ml.dat <- mlogit.data(pizza_marka, choice="fat_cat", shape="wide")
ml <- mlogit(fat_cat ~  0|mois+prot+ash+cal , data=ml.dat, reflevel = 'DUSUK')
summary(ml)
```
```{r}
ml.dat <- mlogit.data(pizza_marka, choice="fat_cat", shape="wide")
ml <- mlogit(fat_cat ~  0|mois+ash+cal , data=ml.dat, reflevel = 'DUSUK')
summary(ml)
```

```{r}
exp(ml$coefficients)
```

```{r}
multi_mo <- multinom(fat_cat ~ mois+prot+ash+cal , data = pizza_marka, model = TRUE)
```

```{r}
PseudoR2(multi_mo, which = c("CoxSnell","Nagelkerke","McFadden"))
```

```{r}
tahminkat<-colnames(ml$probabilities)[max.col(ml$probabilities)]
tahminkat<-as.factor(tahminkat)
```

```{r}
pizza_tab<- table(pizza_marka$fat_cat, tahminkat)
pizza_tab
```

```{r}
sum(diag(pizza_tab)) / sum(pizza_tab)
```



