---
title: "MANOVA_ÇDA"
author: "Yakup Tarık AÇAN / 20181101008"
date: "05 01 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(car)
library(broom)
library(dplyr)
library(tidyr)
library(haven)
library(readxl)
library(dplyr)
library(gplots)
library(biotools)
library(car)
library(heplots)

```

```{r}
pizza_marka <- read_excel("Pizza_data.xlsx")
pizza_marka<-as.data.frame(pizza_marka)
summary(pizza_marka)
pizza_marka$fat_cat[pizza_marka$fat < 15.65] <- "DUSUK"
pizza_marka$fat_cat[pizza_marka$fat >= 15.65 & pizza_marka$fat < 20.3]<- "ORTA"
pizza_marka$fat_cat[pizza_marka$fat >= 20.3]<- "YUKSEK"
pizza_marka$brand<-factor(pizza_marka$brand)
pizza_marka$fat_cat<-factor(pizza_marka$fat_cat)
summary(pizza_marka)
```
```{r}
glimpse(pizza_marka)
```


```{r}
#Grup gozlem dagilimi
pizza_marka %>%
  group_by(brand) %>%
  dplyr::summarise(N = n())

#Degiskenlere Göre Ortalamalar ve Ortalama Çizimleri
#brand duzeyleri bazında degisken ortalamaları ve sapmalar
pizza_marka %>% 
  group_by(brand) %>%
  summarise(across(-fat_cat, list(mean=mean,sd=sd)))

#fat_cat duzeyleri bazında degisken ortalamaları
pizza_marka %>% 
  group_by(fat_cat) %>%
  summarise(across(-brand, list(mean=mean,sd=sd)))
```

```{r}
#brand icin :
plotmeans(sodium~brand,xlab="brand",ylab="tatmin", main="Mean Plot\nwith 95% CI",data=pizza_marka)
plotmeans(carb~brand, xlab="brand",ylab="sahiplenme", main="Mean Plot\nwith 95% CI",data=pizza_marka)
plotmeans(cal~brand, xlab="brand",ylab="kalicilik", main="Mean Plot\nwith 95% CI",data=pizza_marka)

#fat_cat icin :
plotmeans(sodium~fat_cat,xlab="fat_cat",ylab="tatmin", main="Mean Plot\nwith 95% CI",data=pizza_marka)
plotmeans(carb~fat_cat, xlab="fat_cat",ylab="sahiplenme", main="Mean Plot\nwith 95% CI",data=pizza_marka)
plotmeans(cal~fat_cat, xlab="fat_cat",ylab="kalicilik", main="Mean Plot\nwith 95% CI",data=pizza_marka)
```

```{r}
#Multivariate Normality
pizza_marka %>%
  dplyr::select(sodium,carb,cal) %>%
  mshapiro_test()
```

```{r}
box_m(pizza_marka[, c("sodium","carb","cal")], pizza_marka$brand)
```

```{r}
brand_dep_manova <- manova(cbind(sodium,carb,cal) ~ brand,data=pizza_marka)
summary(brand_dep_manova, test = "Hotelling-Lawley")
summary(brand_dep_manova, test = "Wilks")
summary(brand_dep_manova, test = "Pillai")
summary(brand_dep_manova, test = "Roy")
```

```{r}
leveneTest(sodium ~ brand, data=pizza_marka,center=mean)
leveneTest(carb ~ brand, data=pizza_marka,center=mean)
leveneTest(cal ~ brand, data=pizza_marka,center=mean)
```

```{r}
pizza_marka %>% 
  pivot_longer( c(sodium,carb,cal),names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  levene_test(value ~ brand,center=mean)

summary.aov(brand_dep_manova)
```

```{r}
cal_aov <- aov(cal ~ brand, data = pizza_marka)
TukeyHSD(cal_aov, "brand")
```

```{r}
m_tukey2 <- pizza_marka %>%
  pivot_longer( c(cal),names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  tukey_hsd(value ~ brand)
m_tukey2<-m_tukey2[,c(1,2,4,3,5:9)]
m_tukey2
```

```{r}
m_gh_3 <- pizza_marka %>%
  pivot_longer( c(sodium,carb),names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  games_howell_test(value ~ brand,) 
m_gh_3<-m_gh_3[,c(1,2,4,3,5:9)]
m_gh_3
```

```{r}
gh_tek<-games_howell_test(pizza_marka,sodium ~ brand)
gh_tek<-gh_tek[,c(1,3,2,4:8)]
gh_tek
```

# ÇİFT YÖNLÜ MANOVA

```{r}
#pizza_marka$fat_cat_num[pizza_marka$fat_cat == "DUSUK"]<- 0
#pizza_marka$fat_cat_num[pizza_marka$fat_cat == "ORTA"]<- 1
#pizza_marka$fat_cat_num[pizza_marka$fat_cat == "YUKSEK"]<- 2
#boxM( cbind(sodium,carb,cal) ~ brand*fat_cat_num, data=pizza_marka)
```

```{r}
brand_cift <- manova(cbind(sodium,carb,cal) ~ brand*fat_cat,data=pizza_marka)
summary(brand_cift, test = "Wilks")
```

```{r}
pizza_marka %>% 
  pivot_longer( c(sodium,carb,cal),names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  levene_test(value ~ brand*fat_cat,center=mean)
```

```{r}
summary.aov(brand_cift)
```

```{r}
m_tukey22 <- pizza_marka %>%
  pivot_longer( c(sodium,carb,cal),names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  tukey_hsd(value ~ fat_cat*brand)
m_tukey22<-m_tukey22[,c(1,2,4,3,5:9)]
fat_cat_etk<-filter(m_tukey22, term=="fat_cat")
fat_cat_etk
```

```{r}
attach(pizza_marka)
interaction.plot(brand,fat_cat,sodium, fun=mean, type="l", legend=TRUE,col=1:3, lwd=2)
interaction.plot(brand,fat_cat,carb, fun=mean, type="l", legend=TRUE, col=1:3,lwd=2)
interaction.plot(brand,fat_cat,cal, fun=mean, type="l", legend=TRUE, col=1:3,lwd=2)
detach(pizza_marka)
```

```{r}
m2<-pizza_marka[,c(5:9)]
pc_2 <- pizza_marka %>%
  pivot_longer( c(sodium,carb,cal),names_to = "variables", values_to = "value") %>%
  group_by(variables) %>%
  tukey_hsd(value ~ brand*brand)
pc_2<-pc_2[,c(1,2,4,3,5:9)]
pizza_etk<-filter(pc_2, term=="pizza_marka")
pizza_etk
```


